package io.github.mrcoder20.ioclens.core.localization

data class AppStrings(
    val appTitle: String,
    val appTagline: String,
    val skip: String,
    val next: String,
    val previous: String,
    val start: String,
    val changeLanguage: String,
    val searchPlaceholder: String,
    val clear: String,
    val analyzeInstant: String,
    val introGuide: String,
    val enterIndicatorError: String,
    val threatIntelSourcesResults: String,
    val privacyGuardNotice: String,
    val themeLabel: String,
    val languageLabel: String,
    val menuHome: String,
    val menuSettings: String,
    val menuGuide: String,
    val menuProviders: String,
    val menuPrivacyGuard: String,
    val menuAbout: String,
    val settingsTitle: String,
    val appVersion: String,
    val versionLabel: String,
    val systemDefaultTheme: String,
    val darkTheme: String,
    val lightTheme: String,
    val apiKeysTitle: String,
    val autoScanClipboard: String,
    val privacyGuardSetting: String,
    val saveKeys: String,
    val savedSuccessfully: String
)

object LocalizationProvider {
    fun getStrings(language: AppLanguage): AppStrings {
        return when (language) {
            AppLanguage.ENGLISH -> AppStrings(
                appTitle = "IOC Lens",
                appTagline = "Instant, privacy-first threat-indicator triage for defenders",
                skip = "Skip",
                next = "Next →",
                previous = "← Previous",
                start = "Get Started 🚀",
                changeLanguage = "🌐 Language",
                searchPlaceholder = "Enter an IP, domain, URL or file hash...",
                clear = "Clear",
                analyzeInstant = "Instant Lookup ⚡",
                introGuide = "💡 Guide / Intro",
                enterIndicatorError = "Please enter an IP address, domain, URL, or file hash.",
                threatIntelSourcesResults = "Threat Intel Sources Results:",
                privacyGuardNotice = "🛡️ Privacy Guard Activated: Private/Internal indicator detected. Lookup blocked.",
                themeLabel = "Theme",
                languageLabel = "Language",
                menuHome = "Home / Triage",
                menuSettings = "App Settings",
                menuGuide = "Intro Guide",
                menuProviders = "API Keys",
                menuPrivacyGuard = "Privacy Guard",
                menuAbout = "About IOC Lens",
                settingsTitle = "Settings",
                appVersion = "App Version",
                versionLabel = "v1.0.0 (Open Source)",
                systemDefaultTheme = "System Default",
                darkTheme = "Dark Theme",
                lightTheme = "Light Theme",
                apiKeysTitle = "Threat Intel API Keys",
                autoScanClipboard = "Auto-scan Clipboard",
                privacyGuardSetting = "Internal Indicator Guard",
                saveKeys = "Save Settings 💾",
                savedSuccessfully = "Settings updated successfully!"
            )
            AppLanguage.PERSIAN -> AppStrings(
                appTitle = "IOC Lens",
                appTagline = "تریاژ سریع، هوشمند و حریم‌خصوصی‌محور برای تحلیلگران امنیت",
                skip = "رد کردن",
                next = "← بعدی",
                previous = "قبلی →",
                start = "شروع کنید 🚀",
                changeLanguage = "🌐 تغییر زبان",
                searchPlaceholder = "یک IP، دامنه، URL یا هش فایل وارد کنید...",
                clear = "پاک کردن",
                analyzeInstant = "استعلام فوری ⚡",
                introGuide = "💡 راهنما / اینترو",
                enterIndicatorError = "لطفاً یک آدرس IP، دامنه، URL یا هش فایل وارد کنید.",
                threatIntelSourcesResults = "نتایج سرویس‌های Threat Intel:",
                privacyGuardNotice = "🛡️ Privacy Guard فعال شد: نشانگر داخلی/خصوصی شناسایی شد. استعلام مسدود گردید.",
                themeLabel = "تم",
                languageLabel = "زبان",
                menuHome = "صفحه اصلی / تریاژ",
                menuSettings = "تنظیمات برنامه",
                menuGuide = "راهنما و اینترو",
                menuProviders = "کلیدهای API",
                menuPrivacyGuard = "حریم خصوصی",
                menuAbout = "درباره برنامه",
                settingsTitle = "تنظیمات",
                appVersion = "نسخه برنامه",
                versionLabel = "نسخه ۱.۰.۰ (متن‌باز)",
                systemDefaultTheme = "پیش‌فرض سیستم",
                darkTheme = "حالت تاریک",
                lightTheme = "حالت روشن",
                apiKeysTitle = "کلیدهای API سرویس‌های تهدید",
                autoScanClipboard = "اسکن خودکار کلیپ‌بورد",
                privacyGuardSetting = "محافظت از نشانگرهای داخلی",
                saveKeys = "ذخیره تنظیمات 💾",
                savedSuccessfully = "تنظیمات با موفقیت ذخیره شد!"
            )
            AppLanguage.RUSSIAN -> AppStrings(
                appTitle = "IOC Lens",
                appTagline = "Мгновенный триаж индикаторов угроз для аналитиков SOC",
                skip = "Пропустить",
                next = "Далее →",
                previous = "← Назад",
                start = "Начать 🚀",
                changeLanguage = "🌐 Язык",
                searchPlaceholder = "Введите IP, домен, URL или хеш файла...",
                clear = "Очистить",
                analyzeInstant = "Проверить ⚡",
                introGuide = "💡 Руководство",
                enterIndicatorError = "Пожалуйста, введите IP-адрес, домен, URL или хеш файла.",
                threatIntelSourcesResults = "Результаты источников Threat Intel:",
                privacyGuardNotice = "🛡️ Privacy Guard включён: обнаружен внутренний индикатор. Запрос заблокирован.",
                themeLabel = "Тема",
                languageLabel = "Язык",
                menuHome = "Главная / Триаж",
                menuSettings = "Настройки",
                menuGuide = "Руководство",
                menuProviders = "API-ключи",
                menuPrivacyGuard = "Защита данных",
                menuAbout = "О программе",
                settingsTitle = "Настройки",
                appVersion = "Версия",
                versionLabel = "Версия 1.0.0 (Open Source)",
                systemDefaultTheme = "Системная",
                darkTheme = "Тёмная тема",
                lightTheme = "Светлая тема",
                apiKeysTitle = "API-ключи Threat Intel",
                autoScanClipboard = "Автосканирование буфера",
                privacyGuardSetting = "Защита внутренних адресов",
                saveKeys = "Сохранить 💾",
                savedSuccessfully = "Настройки успешно сохранены!"
            )
        }
    }
}
